//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWorkTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALBARAN_X_LINEAS
    {
        public int IdLinea { get; set; }
        public int IdAlbaran { get; set; }
        public int IdProducto { get; set; }
        public string Descripcion { get; set; }
        public double Cantidad { get; set; }
        public double Precio { get; set; }
    
        public virtual ALBARANES ALBARANES { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
