//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWorkTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALBARAN
    {
        public ALBARAN()
        {
            this.LINEA = new HashSet<LINEA>();
        }
    
        public int Id { get; set; }
        public string VALOR1 { get; set; }
        public string VALOR2 { get; set; }
    
        public virtual ICollection<LINEA> LINEA { get; set; }
    }
}
