//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWorkTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINEA
    {
        public LINEA()
        {
            this.ALBARAN = new HashSet<ALBARAN>();
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public int Id { get; set; }
        public int IdProducto { get; set; }
        public double Cantidad { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual ICollection<ALBARAN> ALBARAN { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
