//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWorkTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestEntities : DbContext
    {
        public TestEntities()
            : base("name=TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ALBARAN> ALBARAN { get; set; }
        public DbSet<ALBARAN_X_LINEAS> ALBARAN_X_LINEAS { get; set; }
        public DbSet<ALBARANES> ALBARANES { get; set; }
        public DbSet<FACTURA> FACTURA { get; set; }
        public DbSet<FACTURAS> FACTURAS { get; set; }
        public DbSet<FACTURAS_X_LINEAS> FACTURAS_X_LINEAS { get; set; }
        public DbSet<LINEA> LINEA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
    }
}
