//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWorkTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.ALBARAN_X_LINEAS = new HashSet<ALBARAN_X_LINEAS>();
            this.FACTURAS_X_LINEAS = new HashSet<FACTURAS_X_LINEAS>();
            this.LINEA = new HashSet<LINEA>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public double Costo { get; set; }
    
        public virtual ICollection<ALBARAN_X_LINEAS> ALBARAN_X_LINEAS { get; set; }
        public virtual ICollection<FACTURAS_X_LINEAS> FACTURAS_X_LINEAS { get; set; }
        public virtual ICollection<LINEA> LINEA { get; set; }
    }
}
